// Hockey Position Hero — Scenario Data
// Positions: YOUR team defends LEFT goal. Coordinates are % of rink width/height.
const SCENARIOS = [

  // ═══════════════════════════════════════════════════════════════
  // BEGINNER (1-8) — "Where should I stand?" (static positioning)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 1,
    tier: "beginner",
    position: "RW",
    title: "Stay Between the Puck and Your Goal",
    desc: "The other team has the puck near the boards. Your job is to skate between the puck and your goal so they can't score easily. This is called <b>defensive positioning</b> — always stay on the goal side of the puck!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 24, y: 32, label: "LD" },
      { x: 22, y: 68, label: "RD" },
      { x: 30, y: 45, label: "C" },
      { x: 27, y: 22, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 35, y: 70, label: "LW", hasPuck: true },
      { x: 45, y: 40, label: "RW" },
      { x: 40, y: 55, label: "C" },
      { x: 55, y: 30, label: "LD" },
      { x: 55, y: 65, label: "RD" },
    ],
    youStart: { x: 50, y: 50 },
    target: { x: 28, y: 62, radius: 9 },
    successText: "You got between the puck and your goal! That's how you stop the other team from getting an easy shot.",
    hints: [
      "Think about where your net is (left side) and where the puck is...",
      "You need to be BETWEEN the puck and your net — closer to the left side!",
    ],
    video: { id: "hLwcEyma7L8", title: "Gap Control for Defense", caption: "Watch how the defender keeps the right amount of space between himself and the attacker — not too far, not too close — so he can stop them from getting to the net." },
    playSequence: [
      { target: "you", toX: 30, toY: 65, delay: 0 },
      { target: "puck", toX: 30, toY: 65, delay: 400 },
      { target: "you", toX: 25, toY: 55, delay: 800 },
      { target: "puck", toX: 25, toY: 55, delay: 1000 },
      { target: "puck", toX: 15, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 2,
    tier: "beginner",
    position: "RW",
    title: "Get Open for a Pass",
    desc: "Your teammate has the puck along the boards. Skate to an open area where they can pass to you! Don't stand right next to a defender — find some <b>open ice</b>.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 42, y: 25, label: "LD" },
      { x: 42, y: 75, label: "RD" },
      { x: 65, y: 75, label: "LW", hasPuck: true },
      { x: 58, y: 50, label: "C" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 70, y: 60, label: "RD" },
      { x: 62, y: 35, label: "LD" },
      { x: 55, y: 50, label: "C" },
      { x: 75, y: 45, label: "LW" },
      { x: 65, y: 22, label: "RW" },
    ],
    youStart: { x: 50, y: 75 },
    target: { x: 72, y: 38, radius: 10 },
    successText: "Great spot! You found open ice away from the defenders where your teammate can see you and pass the puck.",
    hints: [
      "Look for space on the ice where no orange defenders are standing...",
      "There's open ice near the far side of the offensive zone — away from the defenders!",
    ],
    video: { id: "bWwTOPsHy_I", title: "How Wings Can Get Open", caption: "Watch how wingers move to open spots on the ice so their teammates can pass to them — it's like finding the empty chair in musical chairs." },
    playSequence: [
      { target: "puck", toX: 72, toY: 38, delay: 0 },
      { target: "you", toX: 78, toY: 35, delay: 500 },
      { target: "puck", toX: 85, toY: 45, delay: 1000 },
      { target: "puck", toX: 88, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 3,
    tier: "beginner",
    position: "LW",
    title: "Cover Your Wing",
    desc: "You're playing left wing. The puck is behind your net with your defenseman. Get to your spot — near the boards on your side, ready for a breakout pass!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 12, y: 35, label: "LD", hasPuck: true },
      { x: 20, y: 65, label: "RD" },
      { x: 22, y: 45, label: "C" },
      { x: 25, y: 80, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 28, y: 40, label: "RW" },
      { x: 32, y: 60, label: "LW" },
      { x: 35, y: 50, label: "C" },
      { x: 48, y: 35, label: "LD" },
      { x: 48, y: 65, label: "RD" },
    ],
    youStart: { x: 20, y: 80 },
    target: { x: 28, y: 18, radius: 9 },
    successText: "Perfect wing position! You're along the boards on your side, ready for the breakout pass.",
    hints: [
      "Wings go to the boards on their side, not behind the net...",
      "Skate up near the boards on the top side — between the circles and the blue line!",
    ],
    video: { id: "Wkc3mHT7BE8", title: "Breakout Tactics for Wings", caption: "Watch where the wingers stand along the boards during a breakout and how they turn their feet to be ready to receive a pass and go." },
    playSequence: [
      { target: "puck", toX: 28, toY: 18, delay: 0 },
      { target: "you", toX: 35, toY: 15, delay: 400 },
      { target: "puck", toX: 50, toY: 15, delay: 800 },
      { target: "you", toX: 55, toY: 18, delay: 1200 },
      { target: "puck", toX: 70, toY: 20, delay: 1600 },
    ],
  },

  {
    id: 4,
    tier: "beginner",
    position: "LW",
    title: "Support the Puck Carrier",
    desc: "Your teammate is skating through the neutral zone with the puck. Don't skate right beside them — keep good <b>spacing</b>! Stay a pass-length away so they have someone to pass to.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 35, y: 70, label: "RD" },
      { x: 33, y: 30, label: "LD" },
      { x: 50, y: 45, label: "C", hasPuck: true },
      { x: 47, y: 75, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 55, y: 55, label: "C" },
      { x: 60, y: 35, label: "LD" },
      { x: 62, y: 65, label: "RD" },
      { x: 52, y: 28, label: "LW" },
      { x: 56, y: 72, label: "RW" },
    ],
    youStart: { x: 30, y: 45 },
    target: { x: 48, y: 22, radius: 10 },
    successText: "Great support! You're close enough to receive a pass but far enough that one defender can't cover both of you.",
    hints: [
      "Don't skate right next to your teammate — spread out! Think about where the defenders AREN'T...",
      "Try the other side of the ice from the defender, keeping up with the puck carrier!",
    ],
    video: { id: "lgSRD24hOU8", title: "Neutral Zone Positioning", caption: "Watch how players spread out in the middle of the ice to give the puck carrier passing options and keep the other team from stealing the puck." },
    playSequence: [
      { target: "puck", toX: 48, toY: 22, delay: 0 },
      { target: "you", toX: 55, toY: 20, delay: 400 },
      { target: "puck", toX: 65, toY: 18, delay: 800 },
      { target: "you", toX: 72, toY: 20, delay: 1200 },
      { target: "puck", toX: 85, toY: 30, delay: 1600 },
    ],
  },

  {
    id: 5,
    tier: "beginner",
    position: "RW",
    title: "Defensive Zone Face-Off",
    desc: "Face-off in your zone! You're the right winger. Stand near the boards on your side, just inside the face-off circle, ready to battle for the puck.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 20, y: 35, label: "LD" },
      { x: 20, y: 65, label: "RD" },
      { x: 23, y: 50, label: "C" },
      { x: 26, y: 25, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 26, y: 50, label: "C", hasPuck: true },
      { x: 30, y: 30, label: "LW" },
      { x: 30, y: 70, label: "RW" },
      { x: 35, y: 40, label: "LD" },
      { x: 35, y: 60, label: "RD" },
    ],
    youStart: { x: 40, y: 25 },
    target: { x: 26, y: 78, radius: 8 },
    successText: "Right where you need to be! You're on your side near the circle, ready to jump on the puck.",
    hints: [
      "For a face-off, you line up near the face-off circle on your side of the ice...",
      "The puck is at the bottom face-off dot — you're the winger on that side, get close to it!",
    ],
    video: { id: "VhKwoN9m_VU", title: "Faceoff Positions for Beginners", caption: "Watch where each player lines up for faceoffs in every zone — everyone has a spot, and knowing yours helps your team win the puck." },
    playSequence: [
      { target: "team-C", toX: 23, toY: 55, delay: 0 },
      { target: "puck", toX: 26, toY: 78, delay: 300 },
      { target: "you", toX: 28, toY: 82, delay: 500 },
      { target: "puck", toX: 20, toY: 65, delay: 900 },
      { target: "team-RD", toX: 18, toY: 60, delay: 1100 },
      { target: "puck", toX: 12, toY: 45, delay: 1500 },
    ],
  },

  {
    id: 6,
    tier: "beginner",
    position: "C",
    title: "Triangle!",
    desc: "Your two teammates have the puck near the opponent's net. You need to form a <b>triangle</b> shape with them — this is the strongest offensive position! Find the spot that completes the triangle up high.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 43, y: 30, label: "LD" },
      { x: 43, y: 70, label: "RD" },
      { x: 82, y: 68, label: "RW", hasPuck: true },
      { x: 78, y: 32, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 78, y: 42, label: "LD" },
      { x: 78, y: 58, label: "RD" },
      { x: 68, y: 50, label: "C" },
      { x: 72, y: 28, label: "LW" },
      { x: 72, y: 72, label: "RW" },
    ],
    youStart: { x: 55, y: 50 },
    target: { x: 72, y: 50, radius: 9 },
    successText: "You completed the triangle! Now your team has three passing options and it's really hard for the defense to cover everyone.",
    hints: [
      "Look at where your two teammates are — what shape could three players make?",
      "Your teammates are low-left and low-right... the triangle point goes higher up, near the blue line area!",
    ],
    video: { id: "CfrkHKZ94CM", title: "Offensive Zone Triangle", caption: "Watch how three forwards form a triangle shape and rotate positions to confuse the defense and create open passing lanes." },
    playSequence: [
      { target: "puck", toX: 72, toY: 50, delay: 0 },
      { target: "you", toX: 75, toY: 48, delay: 400 },
      { target: "puck", toX: 78, toY: 32, delay: 800 },
      { target: "team-LW", toX: 82, toY: 30, delay: 1000 },
      { target: "puck", toX: 86, toY: 48, delay: 1400 },
    ],
  },

  {
    id: 7,
    tier: "beginner",
    position: "RW",
    title: "Back-Check!",
    desc: "The other team stole the puck and is rushing to your goal! You need to <b>back-check</b> — skate hard back and get between the attackers and your net!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 28, y: 38, label: "LD" },
      { x: 30, y: 62, label: "RD" },
      { x: 55, y: 60, label: "C" },
      { x: 60, y: 25, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 40, y: 40, label: "LW", hasPuck: true },
      { x: 38, y: 65, label: "C" },
      { x: 45, y: 55, label: "RW" },
      { x: 50, y: 30, label: "LD" },
      { x: 48, y: 72, label: "RD" },
    ],
    youStart: { x: 65, y: 35 },
    target: { x: 33, y: 55, radius: 9 },
    successText: "Amazing hustle! You got back between the attackers and your goal. That's what back-checking is all about!",
    hints: [
      "Back-check means skating BACK towards your own net — don't stay up high!",
      "Get between the orange players and your goal (left side). Hustle back!",
    ],
    video: { id: "pAjDA-WABXg", title: "The Art of Backchecking", caption: "Watch how forwards skate hard back toward their own net after losing the puck, picking up the other team's players along the way." },
    playSequence: [
      { target: "you", toX: 35, toY: 52, delay: 0 },
      { target: "opp-LW", toX: 35, toY: 42, delay: 300 },
      { target: "puck", toX: 33, toY: 55, delay: 600 },
      { target: "you", toX: 30, toY: 50, delay: 800 },
      { target: "puck", toX: 15, toY: 50, delay: 1200 },
    ],
  },

  {
    id: 8,
    tier: "beginner",
    position: "C",
    title: "Center Lane Breakout",
    desc: "Your defenseman just got the puck behind your net. You're the center — skate to the <b>middle of the ice</b> to give them a safe pass option up the middle!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 10, y: 40, label: "LD", hasPuck: true },
      { x: 18, y: 65, label: "RD" },
      { x: 28, y: 20, label: "LW" },
      { x: 28, y: 80, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 30, y: 50, label: "C" },
      { x: 35, y: 35, label: "LW" },
      { x: 33, y: 65, label: "RW" },
      { x: 50, y: 40, label: "LD" },
      { x: 50, y: 60, label: "RD" },
    ],
    youStart: { x: 15, y: 80 },
    target: { x: 25, y: 50, radius: 9 },
    successText: "You found the middle lane! Now your D can pass it right up the center of the ice.",
    hints: [
      "Centers go to the MIDDLE of the ice during a breakout, not the boards...",
      "Skate to the center of the ice between the face-off circles — right in the middle!",
    ],
    video: { id: "oGMeqSVWDw4", title: "5 Simple Breakout Plays", caption: "Watch five different ways your team can move the puck out of your own zone — look up before you get the puck and know where your teammates are." },
    playSequence: [
      { target: "puck", toX: 25, toY: 50, delay: 0 },
      { target: "you", toX: 35, toY: 48, delay: 400 },
      { target: "puck", toX: 50, toY: 45, delay: 800 },
      { target: "you", toX: 55, toY: 45, delay: 1200 },
      { target: "puck", toX: 70, toY: 40, delay: 1600 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // INTERMEDIATE (9-16) — "Reading the play" (more complex situations)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 9,
    tier: "intermediate",
    position: "RD",
    title: "Cover the Slot",
    desc: "You're the right defenseman. The other team is cycling the puck (passing it around) down low in your zone. Your job is to protect the <b>slot</b> — the dangerous area right in front of your net where most goals are scored!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 20, y: 30, label: "LD" },
      { x: 28, y: 22, label: "LW" },
      { x: 25, y: 45, label: "C" },
      { x: 18, y: 75, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 12, y: 80, label: "RW", hasPuck: true },
      { x: 25, y: 85, label: "LW" },
      { x: 28, y: 55, label: "C" },
      { x: 32, y: 35, label: "LD" },
      { x: 30, y: 70, label: "RD" },
    ],
    youStart: { x: 30, y: 70 },
    target: { x: 22, y: 50, radius: 8 },
    successText: "You're protecting the slot! Even though the puck is in the corner, the most dangerous pass goes to the slot. You took that away!",
    hints: [
      "Where do most goals get scored? Right in front of the net...",
      "The slot is the area right in front of your net — stand between the face-off dots, facing the puck!",
    ],
    video: { id: "o4c-81F0I1o", title: "Defensive Zone Coverage", caption: "Watch how NHL Hall of Famer Denis Savard shows where every player should be in the defensive zone to protect the area right in front of the net." },
    playSequence: [
      { target: "opp-RW", toX: 15, toY: 78, delay: 0 },
      { target: "puck", toX: 25, toY: 85, delay: 400 },
      { target: "opp-LW", toX: 22, toY: 82, delay: 600 },
      { target: "puck", toX: 22, toY: 50, delay: 1000 },
      { target: "you", toX: 22, toY: 50, delay: 1000 },
      { target: "puck", toX: 15, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 10,
    tier: "intermediate",
    position: "LW",
    title: "Cycle Support",
    desc: "You're the left wing. Your teammate has the puck behind the opponent's net and is <b>cycling</b> it (skating around behind the net to confuse the defense). Get to the half-wall (the boards halfway up the zone) so they can pass it to you!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 45, y: 30, label: "LD" },
      { x: 45, y: 70, label: "RD" },
      { x: 72, y: 50, label: "C" },
      { x: 90, y: 55, label: "RW", hasPuck: true },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 80, y: 40, label: "LD" },
      { x: 82, y: 62, label: "RD" },
      { x: 75, y: 50, label: "C" },
      { x: 70, y: 30, label: "LW" },
      { x: 72, y: 72, label: "RW" },
    ],
    youStart: { x: 80, y: 20 },
    target: { x: 68, y: 25, radius: 9 },
    successText: "Perfect half-wall position! Your teammate behind the net can send it up to you, and you have options to shoot or pass.",
    hints: [
      "When a teammate is behind the net, they need someone on the boards halfway up the zone...",
      "Get to the half-wall — that's the boards area about halfway between the goal line and the blue line on your side!",
    ],
    video: { id: "dr3ECi9N2-E", title: "Cycling Basics", caption: "Watch how forwards pass the puck along the boards in the corner and then rotate positions to keep the puck away from the other team." },
    playSequence: [
      { target: "puck", toX: 68, toY: 25, delay: 0 },
      { target: "you", toX: 72, toY: 28, delay: 400 },
      { target: "puck", toX: 75, toY: 40, delay: 800 },
      { target: "puck", toX: 82, toY: 48, delay: 1200 },
      { target: "puck", toX: 88, toY: 50, delay: 1600 },
    ],
  },

  {
    id: 11,
    tier: "intermediate",
    position: "RW",
    title: "Weak-Side Lock",
    desc: "You're the right wing. The puck is on the OTHER side of the ice in your defensive zone. Your job is to <b>lock down your side</b> — stay on the weak side (the side without the puck) so the other team can't make a cross-ice pass to an open player!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 22, y: 35, label: "LD" },
      { x: 18, y: 65, label: "RD" },
      { x: 20, y: 78, label: "C" },
      { x: 14, y: 80, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 15, y: 85, label: "RW", hasPuck: true },
      { x: 25, y: 75, label: "C" },
      { x: 22, y: 20, label: "LW" },
      { x: 30, y: 40, label: "LD" },
      { x: 28, y: 65, label: "RD" },
    ],
    youStart: { x: 35, y: 50 },
    target: { x: 25, y: 25, radius: 9 },
    successText: "Great weak-side lock! You're covering your side of the ice, taking away the dangerous cross-ice pass. Smart defense!",
    hints: [
      "The puck is on the bottom side — where should you be to stop a pass to the top side?",
      "Stay on your side (the top) near the boards, between the face-off circle and the blue line, to cut off that cross-ice pass!",
    ],
    video: { id: "Ikqt_iY4nSA", title: "D-Zone Coverage — Wings", caption: "Watch how the winger on the far side of the puck slides down to cover the slot and protect the front of the net instead of chasing the puck." },
    playSequence: [
      { target: "opp-RW", toX: 18, toY: 82, delay: 0 },
      { target: "puck", toX: 22, toY: 20, delay: 400 },
      { target: "you", toX: 23, toY: 22, delay: 400 },
      { target: "puck", toX: 25, toY: 25, delay: 600 },
      { target: "puck", toX: 15, toY: 50, delay: 1000 },
    ],
  },

  {
    id: 12,
    tier: "intermediate",
    position: "C",
    title: "High Forward",
    desc: "You're the center. Your teammates are working the puck down low in the offensive zone. You need to be the <b>high option</b> — stay near the top of the zone so they can pass it back to you if things get crowded down low.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 42, y: 30, label: "LD" },
      { x: 42, y: 70, label: "RD" },
      { x: 85, y: 70, label: "RW", hasPuck: true },
      { x: 80, y: 30, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 82, y: 42, label: "LD" },
      { x: 82, y: 60, label: "RD" },
      { x: 75, y: 50, label: "C" },
      { x: 70, y: 25, label: "LW" },
      { x: 70, y: 75, label: "RW" },
    ],
    youStart: { x: 78, y: 50 },
    target: { x: 65, y: 50, radius: 9 },
    successText: "You're the high option! If the play down low gets stuck, your teammates can cycle the puck back to you and you can reset the attack or take a shot.",
    hints: [
      "Don't crowd down low with everyone else. Someone needs to stay high...",
      "Stay near the blue line, in the middle of the ice — you're the safety valve if things get tight down low!",
    ],
    video: { id: "CfrkHKZ94CM", title: "Offensive Zone Triangle", caption: "Watch how the high forward stays near the blue line as part of the triangle — they're the safety valve if things get crowded down low." },
    playSequence: [
      { target: "puck", toX: 65, toY: 50, delay: 0 },
      { target: "you", toX: 68, toY: 48, delay: 400 },
      { target: "puck", toX: 80, toY: 30, delay: 800 },
      { target: "team-LW", toX: 82, toY: 35, delay: 1000 },
      { target: "puck", toX: 86, toY: 48, delay: 1400 },
    ],
  },

  {
    id: 13,
    tier: "intermediate",
    position: "LD",
    title: "Pinch or Stay",
    desc: "You're the left defenseman. The puck is loose along the boards near the opponent's blue line on your side. You can <b>pinch</b> (skate forward) to keep the puck in the offensive zone! If you don't, the other team gets a breakout.",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 52, y: 65, label: "RD" },
      { x: 75, y: 28, label: "LW" },
      { x: 78, y: 50, label: "C" },
      { x: 80, y: 72, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 65, y: 18, label: "RW", hasPuck: true },
      { x: 72, y: 40, label: "C" },
      { x: 75, y: 65, label: "LW" },
      { x: 82, y: 35, label: "LD" },
      { x: 80, y: 60, label: "RD" },
    ],
    youStart: { x: 50, y: 25 },
    target: { x: 68, y: 20, radius: 9 },
    successText: "Great pinch! You stepped up to keep the puck in the zone. That keeps your team on offense!",
    hints: [
      "The puck is about to leave your offensive zone. Can you get there to keep it in?",
      "Skate forward along the boards toward the puck — pinch down to the blue line area on your side!",
    ],
    video: { id: "o4c-81F0I1o", title: "Defensive Zone Coverage", caption: "Watch how defensemen decide when to pinch down the boards to keep the puck in the zone versus staying back to prevent a breakaway." },
    playSequence: [
      { target: "you", toX: 68, toY: 18, delay: 0 },
      { target: "puck", toX: 68, toY: 20, delay: 200 },
      { target: "puck", toX: 78, toY: 50, delay: 600 },
      { target: "team-C", toX: 80, toY: 48, delay: 800 },
      { target: "puck", toX: 86, toY: 50, delay: 1200 },
    ],
  },

  {
    id: 14,
    tier: "intermediate",
    position: "C",
    title: "Net-Front Battle",
    desc: "You're the center on the power play (your team has more players on the ice). Park yourself right in front of the opponent's net! You can tip shots (redirect them) and grab <b>rebounds</b> (pucks that bounce off the goalie).",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 65, y: 22, label: "LD" },
      { x: 65, y: 78, label: "RD" },
      { x: 78, y: 25, label: "LW", hasPuck: true },
      { x: 78, y: 75, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 78, y: 42, label: "LD" },
      { x: 78, y: 58, label: "RD" },
      { x: 72, y: 50, label: "C" },
      { x: 70, y: 35, label: "LW" },
    ],
    youStart: { x: 70, y: 50 },
    target: { x: 82, y: 50, radius: 8 },
    successText: "You're planted in front of the net! This is where the dirty goals happen — tips, rebounds, and screens. The goalie can't see the puck with you there!",
    hints: [
      "Where should you stand to tip a shot or grab a rebound?",
      "Get right in front of the opponent's net — as close as you can! That's where rebounds and tips happen!",
    ],
    video: { id: "bWwTOPsHy_I", title: "How Wings Can Get Open", caption: "Watch how forwards park themselves right in front of the net to tip shots and grab rebounds — the goalie can't see past you!" },
    playSequence: [
      { target: "puck", toX: 65, toY: 22, delay: 0 },
      { target: "team-LD", toX: 66, toY: 24, delay: 200 },
      { target: "puck", toX: 85, toY: 48, delay: 600 },
      { target: "puck", toX: 82, toY: 50, delay: 800 },
      { target: "you", toX: 84, toY: 48, delay: 1000 },
      { target: "puck", toX: 88, toY: 50, delay: 1200 },
    ],
  },

  {
    id: 15,
    tier: "intermediate",
    position: "LW",
    title: "Support the Rush",
    desc: "You're the left wing on a <b>2-on-2 rush</b> (two of you vs. two defenders). Your teammate has the puck entering the zone. Don't follow behind them — drive wide (toward the boards) to stretch the defense and create space!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 35, y: 30, label: "LD" },
      { x: 35, y: 70, label: "RD" },
      { x: 62, y: 50, label: "C", hasPuck: true },
      { x: 55, y: 75, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 70, y: 35, label: "LD" },
      { x: 70, y: 60, label: "RD" },
      { x: 60, y: 28, label: "LW" },
      { x: 58, y: 72, label: "RW" },
      { x: 55, y: 50, label: "C" },
    ],
    youStart: { x: 55, y: 40 },
    target: { x: 72, y: 20, radius: 9 },
    successText: "You drove wide! Now the defense has to choose: cover you or the puck carrier. Either way, someone is open!",
    hints: [
      "Don't follow your teammate. Go to a different lane — spread the defense out...",
      "Drive wide toward the boards on your side and get ahead of the puck — make the defense choose who to cover!",
    ],
    video: { id: "Wkc3mHT7BE8", title: "Breakout Tactics for Wings", caption: "Watch how the wide winger drives to the net on a rush, giving the puck carrier a pass option and creating space." },
    playSequence: [
      { target: "team-C", toX: 68, toY: 48, delay: 0 },
      { target: "puck", toX: 72, toY: 20, delay: 400 },
      { target: "you", toX: 78, toY: 22, delay: 600 },
      { target: "puck", toX: 82, toY: 35, delay: 1000 },
      { target: "puck", toX: 88, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 16,
    tier: "intermediate",
    position: "RD",
    title: "Penalty Kill Box",
    desc: "Your team is <b>short-handed</b> (you have fewer players because of a penalty). You're the right defenseman. Form a <b>box</b> with your teammates to protect the area in front of your net. Stay in your corner of the box!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 22, y: 35, label: "LD" },
      { x: 30, y: 35, label: "LW" },
      { x: 30, y: 65, label: "C" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 35, y: 20, label: "LD", hasPuck: true },
      { x: 35, y: 80, label: "RD" },
      { x: 25, y: 80, label: "RW" },
      { x: 25, y: 20, label: "LW" },
      { x: 28, y: 50, label: "C" },
    ],
    youStart: { x: 35, y: 55 },
    target: { x: 25, y: 62, radius: 8 },
    successText: "You completed the box! Your four players are protecting the slot area in a box shape. This is the best way to kill a penalty!",
    hints: [
      "Look at where your three teammates are — they're forming three corners of a box...",
      "You need to be at the bottom-right corner of the box — in front of your net on the bottom side!",
    ],
    video: { id: "XeNryUEVlI8", title: "Penalty Kill: Simple Box", caption: "Watch how four players form a box shape to block passing lanes and protect the front of the net when your team is short one player." },
    playSequence: [
      { target: "opp-LD", toX: 32, toY: 22, delay: 0 },
      { target: "puck", toX: 35, toY: 80, delay: 400 },
      { target: "team-C", toX: 28, toY: 68, delay: 600 },
      { target: "puck", toX: 28, toY: 50, delay: 1000 },
      { target: "you", toX: 26, toY: 58, delay: 1000 },
      { target: "puck", toX: 15, toY: 50, delay: 1400 },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ADVANCED (17-25) — "Game situations" (tactical scenarios)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 17,
    tier: "advanced",
    position: "LD",
    title: "2-on-1 Defense",
    desc: "Uh oh — it's a <b>2-on-1</b>! Two attackers are coming at you and you're the only defenseman back. Don't chase the puck carrier. Instead, take away the <b>pass</b> by staying between the two attackers. Force the puck carrier to shoot!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 45, y: 55, label: "RD" },
      { x: 55, y: 30, label: "C" },
      { x: 60, y: 70, label: "RW" },
      { x: 65, y: 20, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 38, y: 40, label: "C", hasPuck: true },
      { x: 35, y: 70, label: "RW" },
      { x: 55, y: 55, label: "LD" },
      { x: 55, y: 45, label: "RD" },
      { x: 60, y: 35, label: "LW" },
    ],
    youStart: { x: 35, y: 40 },
    target: { x: 28, y: 60, radius: 9 },
    successText: "You took away the pass! The puck carrier has to shoot from a tough angle, and your goalie has a way better chance to save it. That's textbook 2-on-1 defense!",
    hints: [
      "Don't rush at the puck carrier — think about the pass they want to make...",
      "Get between the two attackers, closer to the pass receiver. Your goalie handles the shooter!",
    ],
    video: { id: "Y_NLV-E73RQ", title: "2-on-1 Offense and Defense", caption: "Watch what to do when it's two attackers against one defender — take away the pass and let the goalie handle the shot." },
    playSequence: [
      { target: "opp-C", toX: 30, toY: 42, delay: 0 },
      { target: "you", toX: 25, toY: 58, delay: 200 },
      { target: "puck", toX: 22, toY: 40, delay: 600 },
      { target: "puck", toX: 15, toY: 50, delay: 1000 },
      { target: "team-G", toX: 15, toY: 50, delay: 1000 },
    ],
  },

  {
    id: 18,
    tier: "advanced",
    position: "RW",
    title: "2-on-1 Attack",
    desc: "You have a <b>2-on-1</b> — it's you and your teammate against one defenseman! You're the trailer (the pass option). Stay wide to give your teammate a clear passing lane. Don't skate into the same lane as the puck carrier!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 35, y: 40, label: "LD" },
      { x: 35, y: 60, label: "RD" },
      { x: 30, y: 55, label: "C", hasPuck: true },
      { x: 50, y: 25, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 25, y: 55, label: "LD" },
      { x: 50, y: 50, label: "RD" },
      { x: 55, y: 35, label: "C" },
      { x: 58, y: 65, label: "LW" },
      { x: 60, y: 45, label: "RW" },
    ],
    youStart: { x: 35, y: 50 },
    target: { x: 30, y: 75, radius: 9 },
    successText: "You stayed wide and gave your teammate a clear passing lane! The defenseman can't cover both of you. That's how you score on a 2-on-1!",
    hints: [
      "Don't skate right next to the puck carrier — spread out wide...",
      "Stay on the opposite side from the defenseman, wide near the boards. Give your teammate a clear pass!",
    ],
    video: { id: "Y_NLV-E73RQ", title: "2-on-1 Offense and Defense", caption: "Watch what to do on a 2-on-1 rush — spread apart from your teammate and call for the pass to give the defender an impossible choice." },
    playSequence: [
      { target: "team-C", toX: 25, toY: 52, delay: 0 },
      { target: "puck", toX: 30, toY: 75, delay: 400 },
      { target: "you", toX: 25, toY: 72, delay: 600 },
      { target: "puck", toX: 20, toY: 65, delay: 1000 },
      { target: "puck", toX: 15, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 19,
    tier: "advanced",
    position: "LW",
    title: "3-on-2 Rush",
    desc: "Your team has a <b>3-on-2</b> — three attackers against two defenders! You're the left wing on the wide side. Drive hard to the net from your wing. The two defenders can't cover all three of you!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 40, y: 35, label: "LD" },
      { x: 40, y: 65, label: "RD" },
      { x: 60, y: 50, label: "C", hasPuck: true },
      { x: 58, y: 72, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 70, y: 38, label: "LD" },
      { x: 70, y: 62, label: "RD" },
      { x: 55, y: 25, label: "LW" },
      { x: 55, y: 75, label: "RW" },
      { x: 50, y: 50, label: "C" },
    ],
    youStart: { x: 55, y: 30 },
    target: { x: 75, y: 22, radius: 9 },
    successText: "You drove wide and hard to the net! The two defenders are overwhelmed — your team has numbers. Someone is going to be wide open!",
    hints: [
      "You're the wide player — push up the ice on your side, don't float in the middle...",
      "Drive to the net from your wing! Get to the top side near the net — the defenders can't cover three lanes!",
    ],
    video: { id: "58YEw9bFiXU", title: "Odd Man Rush 3v2", caption: "Watch how three forwards fill the three lanes on a rush and the middle player decides whether to shoot or pass based on what the defenders do." },
    playSequence: [
      { target: "team-C", toX: 68, toY: 48, delay: 0 },
      { target: "team-RW", toX: 72, toY: 70, delay: 200 },
      { target: "you", toX: 78, toY: 25, delay: 400 },
      { target: "puck", toX: 75, toY: 22, delay: 800 },
      { target: "puck", toX: 85, toY: 40, delay: 1200 },
      { target: "puck", toX: 88, toY: 50, delay: 1600 },
    ],
  },

  {
    id: 20,
    tier: "advanced",
    position: "LD",
    title: "Power Play Umbrella",
    desc: "Your team is on the <b>power play</b> (you have an extra player)! You're the left defenseman — the point man. Stay high near the blue line. From there you can pass to either side or take a <b>one-timer</b> (a slap shot right off a pass)!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 65, y: 70, label: "RD" },
      { x: 80, y: 30, label: "LW" },
      { x: 82, y: 50, label: "C" },
      { x: 80, y: 70, label: "RW", hasPuck: true },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 78, y: 42, label: "LD" },
      { x: 78, y: 58, label: "RD" },
      { x: 72, y: 50, label: "C" },
      { x: 72, y: 35, label: "LW" },
    ],
    youStart: { x: 55, y: 40 },
    target: { x: 65, y: 25, radius: 9 },
    successText: "You're at the point! From here you can see the whole zone and take a big slap shot or pass to your teammates. The umbrella power play is all about that top position!",
    hints: [
      "The point man stays HIGH, near the blue line — don't go too deep into the zone...",
      "Get to the blue line area on your side (top of the zone). That's the top of the umbrella shape!",
    ],
    video: { id: "QKhE3UAzhqo", title: "Powerplay Setups Explained", caption: "Watch the three main power play formations and see how players spread out to move the puck around the penalty killers for a good shot." },
    playSequence: [
      { target: "puck", toX: 65, toY: 25, delay: 0 },
      { target: "you", toX: 66, toY: 28, delay: 400 },
      { target: "puck", toX: 80, toY: 30, delay: 800 },
      { target: "team-LW", toX: 82, toY: 32, delay: 1000 },
      { target: "puck", toX: 86, toY: 48, delay: 1400 },
    ],
  },

  {
    id: 21,
    tier: "advanced",
    position: "C",
    title: "PK Pressure",
    desc: "Your team is <b>killing a penalty</b> (you're short one player). The other team's defenseman has the puck at the point (near the blue line). Your job is to <b>pressure</b> them — skate at them to block the shot or force a bad pass!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 22, y: 40, label: "LD" },
      { x: 22, y: 60, label: "RD" },
      { x: 30, y: 65, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 60, y: 28, label: "LD", hasPuck: true },
      { x: 60, y: 72, label: "RD" },
      { x: 30, y: 20, label: "LW" },
      { x: 30, y: 80, label: "RW" },
      { x: 28, y: 50, label: "C" },
    ],
    youStart: { x: 40, y: 50 },
    target: { x: 62, y: 30, radius: 8 },
    successText: "You pressured the point! Now they can't take an easy shot and have to rush their pass. Aggressive penalty killing is the best penalty killing!",
    hints: [
      "Don't just stand back — go get the player with the puck!",
      "Skate out toward the opponent with the puck at the point. Pressure them so they can't get a clean shot!",
    ],
    video: { id: "XeNryUEVlI8", title: "Penalty Kill: Simple Box", caption: "Watch how the penalty kill pressures the puck carrier at the point to force a bad pass or take away time on the power play." },
    playSequence: [
      { target: "you", toX: 58, toY: 30, delay: 0 },
      { target: "opp-LD", toX: 58, toY: 25, delay: 200 },
      { target: "puck", toX: 60, toY: 72, delay: 600 },
      { target: "team-RW", toX: 35, toY: 68, delay: 800 },
      { target: "puck", toX: 35, toY: 68, delay: 1000 },
      { target: "puck", toX: 50, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 22,
    tier: "advanced",
    position: "LW",
    title: "Forecheck F1",
    desc: "Your team just dumped the puck into the opponent's zone. You're <b>F1</b> — the first forward in! Your job is to angle the puck carrier toward the boards (not let them skate up the middle). Cut off the middle of the ice!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 50, y: 30, label: "LD" },
      { x: 50, y: 70, label: "RD" },
      { x: 68, y: 50, label: "C" },
      { x: 65, y: 72, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 85, y: 25, label: "LD", hasPuck: true },
      { x: 88, y: 65, label: "RD" },
      { x: 80, y: 40, label: "C" },
      { x: 78, y: 25, label: "LW" },
      { x: 78, y: 75, label: "RW" },
    ],
    youStart: { x: 70, y: 20 },
    target: { x: 82, y: 30, radius: 8 },
    successText: "Great angle! You cut off the middle and forced the puck carrier to the boards. Now your teammates can finish the forecheck and trap them!",
    hints: [
      "Don't skate straight at the puck carrier — take an angle to cut off the middle of the ice...",
      "Approach from the inside (middle) so you push them toward the boards. You want to be between them and center ice!",
    ],
    video: { id: "cOR--Fi5KoU", title: "Forechecking: Dog, Fox, Hawk", caption: "Watch how the first forward (the Dog) chases the puck carrier and angles them toward the boards to force a turnover." },
    playSequence: [
      { target: "you", toX: 83, toY: 28, delay: 0 },
      { target: "opp-LD", toX: 82, toY: 18, delay: 300 },
      { target: "team-C", toX: 75, toY: 30, delay: 600 },
      { target: "puck", toX: 75, toY: 30, delay: 800 },
      { target: "puck", toX: 82, toY: 48, delay: 1200 },
      { target: "puck", toX: 88, toY: 50, delay: 1600 },
    ],
  },

  {
    id: 23,
    tier: "advanced",
    position: "C",
    title: "Forecheck F2",
    desc: "You're the center, the <b>second forward in</b> on the forecheck (F2). Your left wing (F1) is pressuring the puck carrier on the boards. Your job is to cut off the <b>D-to-D pass</b> — get between the two defensemen so they can't pass it across!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 55, y: 30, label: "LD" },
      { x: 55, y: 70, label: "RD" },
      { x: 85, y: 25, label: "LW" },
      { x: 70, y: 72, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 85, y: 20, label: "LD", hasPuck: true },
      { x: 82, y: 65, label: "RD" },
      { x: 75, y: 35, label: "C" },
      { x: 72, y: 20, label: "LW" },
      { x: 72, y: 75, label: "RW" },
    ],
    youStart: { x: 65, y: 45 },
    target: { x: 78, y: 50, radius: 9 },
    successText: "You cut off the D-to-D pass! Now the puck carrier is stuck on the boards with no easy outlet. Your team can force a turnover!",
    hints: [
      "F2 doesn't chase the puck — F2 takes away the escape pass...",
      "Get between the two defensemen (the one with the puck and the other one). Don't let them pass across!",
    ],
    video: { id: "cOR--Fi5KoU", title: "Forechecking: Dog, Fox, Hawk", caption: "Watch how the second forward (the Fox) reads where the puck is going and cuts off the escape pass while the first forward pressures." },
    playSequence: [
      { target: "team-LW", toX: 84, toY: 22, delay: 0 },
      { target: "you", toX: 80, toY: 48, delay: 200 },
      { target: "opp-LD", toX: 83, toY: 18, delay: 400 },
      { target: "puck", toX: 80, toY: 48, delay: 800 },
      { target: "you", toX: 82, toY: 45, delay: 1000 },
      { target: "puck", toX: 86, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 24,
    tier: "advanced",
    position: "RD",
    title: "D-Zone Rotation",
    desc: "Your defensive partner (the left defenseman) got beat — the attacker blew right past them! You need to <b>rotate over</b> and cover their spot in front of the net. Don't leave the front of the net open!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 12, y: 22, label: "LD" },
      { x: 25, y: 75, label: "C" },
      { x: 18, y: 85, label: "RW" },
      { x: 22, y: 20, label: "LW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 15, y: 28, label: "RW", hasPuck: true },
      { x: 20, y: 50, label: "C" },
      { x: 25, y: 70, label: "LW" },
      { x: 30, y: 30, label: "LD" },
      { x: 28, y: 60, label: "RD" },
    ],
    youStart: { x: 25, y: 60 },
    target: { x: 18, y: 40, radius: 8 },
    successText: "You rotated over! Your partner got beat but you filled in and protected the front of the net. That's what great defensive partners do — they cover for each other!",
    hints: [
      "Your partner is out of position — who's going to cover the front of the net?",
      "Slide over toward the net to cover the area your partner left open. Get between the attackers and the goal!",
    ],
    video: { id: "cKC1wnWyGcw", title: "Defensive Zone Rotation", caption: "Watch how all five players slide together as a unit when the puck moves across the zone, like a door swinging on a hinge." },
    playSequence: [
      { target: "you", toX: 18, toY: 42, delay: 0 },
      { target: "opp-RW", toX: 18, toY: 30, delay: 300 },
      { target: "puck", toX: 20, toY: 50, delay: 600 },
      { target: "you", toX: 19, toY: 45, delay: 600 },
      { target: "puck", toX: 18, toY: 40, delay: 1000 },
      { target: "puck", toX: 15, toY: 50, delay: 1400 },
    ],
  },

  {
    id: 25,
    tier: "advanced",
    position: "C",
    title: "Neutral Zone Regroup",
    desc: "Your team has the puck but got clogged in the <b>neutral zone</b> — too many players in one area! As the center, come back toward your own zone to support the puck carrier. This is called a <b>regroup</b> — sometimes you have to go backward to go forward!",
    teamPlayers: [
      { x: 15, y: 50, label: "G" },
      { x: 45, y: 35, label: "LD", hasPuck: true },
      { x: 45, y: 65, label: "RD" },
      { x: 55, y: 22, label: "LW" },
      { x: 55, y: 78, label: "RW" },
    ],
    oppPlayers: [
      { x: 88, y: 50, label: "G" },
      { x: 55, y: 42, label: "C" },
      { x: 58, y: 28, label: "LW" },
      { x: 58, y: 72, label: "RW" },
      { x: 65, y: 35, label: "LD" },
      { x: 65, y: 65, label: "RD" },
    ],
    youStart: { x: 55, y: 50 },
    target: { x: 40, y: 50, radius: 9 },
    successText: "Smart regroup! You came back to support the play. Now your defenseman has a safe pass and your team can reorganize. Sometimes going backward is the smartest play!",
    hints: [
      "The neutral zone is clogged. Sometimes the best play is to come back and reset...",
      "Skate back toward your own zone to give the puck carrier a safe pass option. Regroup and try again!",
    ],
    video: { id: "J1jymsyBzQE", title: "Neutral Zone Regroup Options", caption: "Watch how your team circles back to regroup when they can't enter the offensive zone, using post-up, curl, and stretch options." },
    playSequence: [
      { target: "puck", toX: 40, toY: 50, delay: 0 },
      { target: "you", toX: 42, toY: 48, delay: 400 },
      { target: "team-LW", toX: 58, toY: 20, delay: 600 },
      { target: "puck", toX: 55, toY: 22, delay: 1000 },
      { target: "team-LW", toX: 68, toY: 25, delay: 1200 },
      { target: "puck", toX: 75, toY: 30, delay: 1600 },
    ],
  },

];
